export default function Recipe() {
  let item = JSON.parse(sessionStorage.getItem('item'));

  return (
    <div>
      <h2>{item.strMeal}</h2>
      <div id="ingredientPage">
        <table id="ingredients">
          <tbody>
            <tr>
              <th colSpan="2">Ingredients</th>
            </tr>
            <tr>
              <td>{item.strIngredient1}</td>
              <td>{item.strMeasure1}</td>
            </tr>
            <tr>
              <td>{item.strIngredient2}</td>
              <td>{item.strMeasure2}</td>
            </tr>
            <tr>
              <td>{item.strIngredient3}</td>
              <td>{item.strMeasure4}</td>
            </tr>
            <tr>
              <td>{item.strIngredient4}</td>
              <td>{item.strMeasure4}</td>
            </tr>
            <tr>
              <td>{item.strIngredient5}</td>
              <td>{item.strMeasure5}</td>
            </tr>
            <tr>
              <td>{item.strIngredient6}</td>
              <td>{item.strMeasure6}</td>
            </tr>
            <tr>
              <td>{item.strIngredient7}</td>
              <td>{item.strMeasure7}</td>
            </tr>
            <tr>
              <td>{item.strIngredient8}</td>
              <td>{item.strMeasure8}</td>
            </tr>
            <tr>
              <td>{item.strIngredient9}</td>
              <td>{item.strMeasure9}</td>
            </tr>
            <tr>
              <td>{item.strIngredient10}</td>
              <td>{item.strMeasure10}</td>
            </tr>
            <tr>
              <td>{item.strIngredient11}</td>
              <td>{item.strMeasure11}</td>
            </tr>
            <tr>
              <td>{item.strIngredient12}</td>
              <td>{item.strMeasure12}</td>
            </tr>
            <tr>
              <td>{item.strIngredient13}</td>
              <td>{item.strMeasure13}</td>
            </tr>
            <tr>
              <td>{item.strIngredient14}</td>
              <td>{item.strMeasure14}</td>
            </tr>
            <tr>
              <td>{item.strIngredient15}</td>
              <td>{item.strMeasure15}</td>
            </tr>
            <tr>
              <td>{item.strIngredient16}</td>
              <td>{item.strMeasure16}</td>
            </tr>
            <tr>
              <td>{item.strIngredient17}</td>
              <td>{item.strMeasure17}</td>
            </tr>
            <tr>
              <td>{item.strIngredient18}</td>
              <td>{item.strMeasure18}</td>
            </tr>
            <tr>
              <td>{item.strIngredient19}</td>
              <td>{item.strMeasure19}</td>
            </tr>
            <tr>
              <td>{item.strIngredient20}</td>
              <td>{item.strMeasure20}</td>
            </tr>
          </tbody>
        </table>
        <p id="instructions">{item.strInstructions}</p>
      </div>
    </div>
  );
}
